name: NPM Release

on:
  release:
    types:
      - released

env:
  CI: true

permissions:
  id-token: write

jobs:
  publish:
    name: Build & Publish to Crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Clean variable
        id: version
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Edit Toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "version"
          value: "${{ steps.version.outputs.VERSION }}"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}