name: NPM Release

on:
  release:
    types:
      - released
  pull_request:

env:
  CI: true

permissions:
  id-token: write

jobs:
  publish:
    name: Build & Publish to Crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Clean variable
        id: version
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install toml-cli
      - name: Edit Toml version
        run: toml set --toml-path Cargo.toml package.version $VERSION
        env:
          VERSION: "${{ steps.version.outputs.VERSION }}"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cat Cargo.toml
      - uses: katyo/publish-crates@v2
        if: github.event_name == 'push'
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}